Added first assert type

diff --git a/shUnit b/shUnit
--- a/shUnit
+++ b/shUnit
@@ -4,53 +4,76 @@ RED='\033[0;31m'
 GREEN='\033[0;32m'
 BLUE='\033[0;35m'
 NC='\033[0m' # No Color
+trap "" SIGHUP
 
-
+source assert.sh
 shopt -s globstar
 
 function setup {
-    return
+    return 0
 }
 function destroy {
-    return
+    return 0
 }
 function setupTest {
-    return
+    return 0
 }
 function destroyTest {
-    return
+    return 0
 }
 
-# execute all test in a single unit $1 is the units file name
+# $1 is the unit filename
+# $2 is the function name
+function run-function {
+                source "$1"
+                echo -e "$BLUE Running test: $2 $NC"
+                setupTest || echo -e "${RED}Error: running setupTest${NC}"
+
+                "$2"
+
+                destroyTest || echo -e "${RED}Error: running destroyTest${NC}"
+}
+
+# execute all test in a single unit $1 is the shUnit filename $2 is the units file name
 function execute-test {
-        func=$(grep "function Test.*{" "$1" | sed 's:function ::' | sed 's: {::')
+        func=$(grep "function Test.*{" "$2" | sed 's:function ::' | sed 's: {::')
         for unitTest in $func; do
-                echo -e "$BLUE Running test: $unitTest $NC"
-                setupTest
-                "$unitTest"
-                destroyTest
+                "$1" -f "$2" "$unitTest"
         done
 }
 
-# $1 is the file
+# $1 is the shUnit
+# $2 is the unitfile to be ran
 function run-unit {
     # get the file comment
-    desc=$(head -n1 "$1" | sed 's:^#::')
+    desc=$(head -n1 "$2" | sed 's:^#::')
     # print out the file comment
     echo -e "$BLUE$desc$NC"
     # load in the file
-    source "$1"
+    source "$2"
     # perform initial setup
-    setup
+    setup || echo -e "${RED}Error: running setup${NC}"
     
-    execute-test "$1"
+    execute-test "$1" "$2"
 
     # perform destruction
-    destroy
+    destroy || echo -e "${RED} Error: running destroy${NC}"
+}
+
+function reset {
+        if [[ -d ".shunit" ]]; then
+                rm -rf .shunit
+        fi
+        mkdir .shunit
+        touch .shunit/pass
+        touch .shunit/error
+
+
 }
 
 # $1 is the path to shUnit
 function iterate {
+    reset
     for unit in **/*.shUnit; do
         if [[ -f "$unit" ]]; then
            echo -e "$BLUE Running unit: $NC$unit"
@@ -58,11 +81,19 @@ function iterate {
            echo -e "$BLUE--------------------------------------------------------$NC"
         fi
     done 
+    pass=$(wc -l .shunit/pass | awk '{print $1}')
+    error=$(wc -l .shunit/error | awk '{print $1}')
+    echo "Pass: $pass, Errors: $error"
+    if [[ "$error" -gt "0" ]]; then
+            exit 1
+    fi
 }
 
 
 if [[ "$1" == "-r" ]]; then
-        run-unit "$2"
+        run-unit "$0" "$2"
+elif [[ "$1" == "-f" ]]; then
+        run-function "$2" "$3"
 else
         iterate "$0"
 fi
